app_name: Echo Trial
app_version: 0.0.1
app_env: dev

dev:
  adapter: mysql
  database: try_echo
  username: root
  password: root
  host: mysql.dev     #defaults to 127.0.0.1
  port: 3306
  idle_conns: 10
  open_conns: 100
  sslmode: disable

staging:
  adapter: postgre
  database: try_echo
  username: yourusername
  password: yourpassword
  host: 0.0.0.0     #defaults to 127.0.0.1
  port: 5432
  idle_conns: 10
  open_conns: 100
  sslmode: disable

production:
  adapter: postgre
  database: try_echo
  username: yourusername
  password: yourpassword
  host: 0.0.0.0     #defaults to 127.0.0.1
  port: 5432
  idle_conns: 10
  open_conns: 100
  sslmode: disable